version: "3.9"

services:
  football-web:
    image: football-app:latest
    container_name: football-web
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      SECRET_KEY: password
      DATABASE_URL: postgresql://pickarena_app_user:Silkyjungle432!@10.0.0.129:5432/pickarena_prod_db
      DISABLE_APSCHEDULER: "1"
    restart: unless-stopped

  football-scheduler:
    image: football-app:latest
    container_name: football-scheduler
    command: ["python", "scheduler_runner.py"]
    environment:
      SECRET_KEY: password
      DATABASE_URL: postgresql://pickarena_app_user:Silkyjungle432!@10.0.0.129:5432/pickarena_prod_db
      DISABLE_APSCHEDULER: "0"
    restart: unless-stopped
