"""add reminder jobs

Revision ID: 3e4aa4248eb6
Revises: 9f4960deba3e
Create Date: 2026-04-28 10:04:12.888335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e4aa4248eb6'
down_revision = '9f4960deba3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('season_type', sa.String(length=10), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('reminder_type', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['pool_group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'season_year', 'season_type', 'week', 'reminder_type', 'channel', name='uq_reminder_once')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('uq_user_email_active', postgresql_where='(is_active = true)')
        batch_op.drop_index('uq_user_username_active', postgresql_where='(is_active = true)')
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('uq_user_username_active', ['username'], unique=True, postgresql_where='(is_active = true)')
        batch_op.create_index('uq_user_email_active', ['email'], unique=True, postgresql_where='(is_active = true)')

    op.drop_table('reminder_job')
    # ### end Alembic commands ###
