"""harden sms_opt_in to not null with default false

Revision ID: 4bf07f95f7a2
Revises: b03e9f924941
Create Date: 2025-09-11 23:11:42.896362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bf07f95f7a2'
down_revision = 'b03e9f924941'
branch_labels = None
depends_on = None


def upgrade():
    # Backfill existing NULLs to false
    op.execute('UPDATE "user" SET sms_opt_in = 0 WHERE sms_opt_in IS NULL')

    # Enforce NOT NULL + server default
    with op.batch_alter_table('user') as batch_op:
        batch_op.alter_column(
            'sms_opt_in',
            existing_type=sa.Boolean(),
            nullable=False,
            server_default=sa.text('false')
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('sms_opt_in',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
