"""add job_run

Revision ID: 7aa56a95f8fc
Revises: e2352d36d95f
Create Date: 2026-01-07 15:59:55.380423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aa56a95f8fc'
down_revision = 'e2352d36d95f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=50), nullable=False),
    sa.Column('ran_at', sa.DateTime(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('inserted', sa.Integer(), nullable=True),
    sa.Column('updated', sa.Integer(), nullable=True),
    sa.Column('unchanged', sa.Integer(), nullable=True),
    sa.Column('failed_weeks', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_run_job_name'), ['job_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_run_job_name'))

    op.drop_table('job_run')
    # ### end Alembic commands ###
