"""add is_active to user model

Revision ID: 9f4960deba3e
Revises: bf402f70920f
Create Date: 2026-04-23 08:39:10.416959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f4960deba3e'
down_revision = 'bf402f70920f'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Add column as nullable first
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=True))

    # 2. Backfill existing rows
    op.execute('UPDATE "user" SET is_active = true')

    # 3. Make it NOT NULL
    op.alter_column('user', 'is_active', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
