"""adding group invite to db

Revision ID: bf402f70920f
Revises: 9349093b0ef4
Create Date: 2026-04-22 09:24:18.092320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf402f70920f'
down_revision = '9349093b0ef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_invite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['pool_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('group_invite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_invite_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_invite_token'), ['token'], unique=True)

    with op.batch_alter_table('group_member', schema=None) as batch_op:
        batch_op.drop_index('ix_group_member_group_id')
        batch_op.drop_index('ix_group_member_user_id')

    with op.batch_alter_table('pick', schema=None) as batch_op:
        batch_op.drop_index('ix_pick_group_id')

    with op.batch_alter_table('user_score', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_score_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_score', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_score_user_id'))

    with op.batch_alter_table('pick', schema=None) as batch_op:
        batch_op.create_index('ix_pick_group_id', ['group_id'], unique=False)

    with op.batch_alter_table('group_member', schema=None) as batch_op:
        batch_op.create_index('ix_group_member_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_group_member_group_id', ['group_id'], unique=False)

    with op.batch_alter_table('group_invite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_invite_token'))
        batch_op.drop_index(batch_op.f('ix_group_invite_group_id'))

    op.drop_table('group_invite')
    # ### end Alembic commands ###
