"""add job_run table

Revision ID: e2352d36d95f
Revises: 8be601664434
Create Date: 2026-01-07 14:11:29.227237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2352d36d95f'
down_revision = '8be601664434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('week',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index('idx_game_season')
        batch_op.drop_index('uq_game_season_type_game_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.create_index('uq_game_season_type_game_id', ['season_year', 'season_type', 'game_id'], unique=True)
        batch_op.create_index('idx_game_season', ['season_year', 'season_type'], unique=False)
        batch_op.alter_column('week',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
